export const homeData = [
  {
    id: 1,
    name: "Jurassic World",
    rating: 6.9,
    time: "2hr : 22mins",
    desc: "A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree.",
    starring: "Chris PrattBryce Dallas HowardTy Simpkins",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home1.jpg",
    video: "https://youtu.be/jan5CFWs9ic?si=jayhZd_zanHl7XEM",
    date: "June-12-2015",
  },
  {
    id: 2,
    name: "The Dark Knight",
    rating: 9.0,
    time: "2hr : 23mins",
    desc: "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness. ",
    starring: "Christian BaleHeath LedgerAaron Eckhart",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/home2.jpg",
    video: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Need for Speed",
    rating: 6.4,
    time: "2hr : 22mins",
    desc: "Fresh from prison, a street racer who was framed by a wealthy business associate joins a cross-country race with revenge in mind. His ex-partner, learning of the plan, places a massive bounty on his head as the race begins.",
    starring: "Aaron PaulDominic CooperImogen Poots",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "https://youtu.be/u3wtVI-aJuw?si=qI-aDf5Om4CtAwoW",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Godzilla",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home4.jpg",
    video: "https://youtu.be/TtY648EsJNA?si=2GJ5Ja7qkF9Ul2C-",
    date: "12-Aug-2015",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]